version: '1.0'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_pw
    volumes: 
      - cache:/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongodb:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # mongo-express portal username and password
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #connection to mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  api:
    container_name: vahshipanda-api
    build:
      context: .
      dockerfile: api.Dockerfile
      # target: production
      # args:
    image: vahshipanda-api
    depends_on:
      - db
      - cache
    ports:
      - 9000:5000
    environment:
      NODE_ENV: model
      MONGODBDB_HOST: db
      MONGODBDB_USERNAME: postgres 
      MONGODBDB_PASSWORD: postgres
      MONGODBDB_PORT: 5432
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pw
    links:
      - db
      - cache
    volumes:
      - ./api:/app

  chat:
    container_name: vahshipanda-chat
    build:
      context: .
      dockerfile: chat.Dockerfile
      # target: production
      # args:
    image: vahshipanda-chat
    depends_on:
      - mongo
      - cache
      - api
    ports:
      - 9001:5000
    environment:
      NODE_ENV: model
      MONGODBDB_HOST: mongo
      MONGODBDB_PORT: 27017
      MONGODBDB_USER: root
      MONGODBDB_PASSWORD: example
      API_HOST: vahshipanda-api
      API_PORT: 5000
      # DB_NAME: postgres
      # REDIS_HOST: cache
      # REDIS_PORT: 6379
      # REDIS_PASSWORD: redis_pw
    links:
      - mongo
      - cache
      - api
    volumes:
      - ./chat:/app


volumes:
  db:
    driver: local
  cache:
    driver: local
  mongodb:
    driver: local