name: Coverity Scan
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  upload-to-coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tar czf App_cov_scan.tgz app
      - run: curl --form token=${{ secrets.COVERITY_TOKEN}} \
              --form email=james.chen.9415@gmail.com \
              --form file=@App_cov_scan.tgz \
              --form version="Version" \
              --form description="Description" \
              https://scan.coverity.com/builds?project=VahshiPanda-Server
