name: Coverity Scan
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  upload-to-coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=VahshiPanda-Server" -O coverity_tool.tgz
      - run: tar xzf coverity_tool.tgz
      - run: ls -al
      - run: ls -al ../cov-analysis-linux64-*/bin/cov-build
      # - run: ../cov-analysis-linux64-*/bin/cov-build --dir ../cov-int --no-command --fs-capture-search ./app
      # - run: tar czvf App_cov_scan.tgz cov-int
      # - run: curl --form token=${{ secrets.COVERITY_TOKEN }} \
      #         --form email=james.chen.9415@gmail.com \
      #         --form file=@App_cov_scan.tgz \
      #         --form version="Version" \
      #         --form description="Description" \
      #         https://scan.coverity.com/builds?project=VahshiPanda-Server
